project_id = "ssuingprkeergtpxtsji"

[functions.accept-friend-request]
verify_jwt = true

[functions.analyze-closet-item]
verify_jwt = true

[functions.analyze-body-shape]
verify_jwt = true

[functions.generate-outfit-recommendations]
verify_jwt = true

[functions.generate-avatar]
verify_jwt = true
